"""followers

Revision ID: 124ab0d92dc4
Revises: 63bdd4b42452
Create Date: 2023-11-08 08:28:23.281006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '124ab0d92dc4'
down_revision = '63bdd4b42452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
